import logging
from typing import Any, AsyncIterator

from openai import AsyncOpenAI

from backend.core.config import settings
from backend.services.vector_service import VectorService

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are a helpful AI assistant. Answer the user's question strictly based on the provided context.
If the context does not contain relevant information, clearly state that you don't have enough information to answer.
Do NOT make up information that is not supported by the context.

CONTEXT:
{context}
"""


class RAGService:
    """Orchestrates the full Retrieval-Augmented Generation (RAG) pipeline.

    The pipeline for each query is:
        1. Retrieve: Perform a tenant-scoped similarity search in Qdrant.
        2. Augment: Build a structured prompt injecting the retrieved context.
        3. Generate: Call the LLM (gpt-4o-mini) to produce the final answer.

    This service enforces tenant isolation by delegating all vector operations
    to VectorService, which mandates tenant_id filtering on every query.
    """

    def __init__(self, vector_service: VectorService) -> None:
        self._openai = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)
        self._vector_service = vector_service

    async def generate_answer(
        self,
        tenant_id: str,
        query: str,
        chat_history: list[dict[str, str]] | None = None,
    ) -> dict[str, Any]:
        """Runs the full RAG pipeline and returns the generated answer with sources.

        Args:
            tenant_id: The tenant ID scoping this request. Used for mandatory Qdrant filter.
            query: The user's question string.
            chat_history: Optional list of previous messages as
                          [{"role": "user"/"assistant", "content": "..."}].

        Returns:
            A dict with:
                - "answer" (str): The generated response from the LLM.
                - "sources" (list[dict]): The context chunks used for generation.
                - "model" (str): The LLM model name used.
        """
        # Step 1: Retrieve relevant context chunks from Qdrant (tenant-isolated)
        context_chunks = await self._vector_service.search_similar_chunks(
            tenant_id=tenant_id,
            query=query,
        )

        if not context_chunks:
            logger.info(
                "No relevant context found for query='%s...' (tenant='%s').",
                query[:50], tenant_id,
            )
            return {
                "answer": "I could not find any relevant information in the knowledge base to answer your question.",
                "sources": [],
                "model": settings.LLM_MODEL,
            }

        # Step 2: Augment — format context for the system prompt
        context_text = "\n\n---\n\n".join(
            f"[Source: {chunk['source']}, Chunk #{chunk['chunk_index']}]\n{chunk['text']}"
            for chunk in context_chunks
        )

        system_message = SYSTEM_PROMPT.format(context=context_text)
        logger.debug(
            "Built prompt with %d context chunks for tenant='%s'.",
            len(context_chunks), tenant_id,
        )

        # Step 3: Generate — call OpenAI LLM with optional chat history
        messages: list[dict[str, str]] = [{"role": "system", "content": system_message}]
        if chat_history:
            messages.extend(chat_history)
        messages.append({"role": "user", "content": query})

        response = await self._openai.chat.completions.create(
            model=settings.LLM_MODEL,
            messages=messages,
            temperature=0.2,  # Low temperature for factual, grounded responses
        )

        answer = response.choices[0].message.content or ""
        logger.info(
            "Generated answer using model='%s' for tenant='%s' (context_chunks=%d).",
            settings.LLM_MODEL, tenant_id, len(context_chunks),
        )

        return {
            "answer": answer,
            "sources": context_chunks,
            "model": settings.LLM_MODEL,
        }

    async def stream_answer(
        self,
        tenant_id: str,
        query: str,
        chat_history: list[dict[str, str]] | None = None,
    ) -> AsyncIterator[dict]:
        """Runs the RAG pipeline and streams the LLM response token by token.

        This is the preferred method for frontend integration as it enables
        ChatGPT-like incremental response display.

        Args:
            tenant_id: The tenant ID for mandatory Qdrant isolation.
            query: The user's question string.
            chat_history: Optional list of previous messages.

        Yields:
            String tokens as they are generated by the LLM.
        """
        # Step 1: Retrieve context (same tenant-isolated search)
        context_chunks = await self._vector_service.search_similar_chunks(
            tenant_id=tenant_id,
            query=query,
        )

        if not context_chunks:
            yield {"type": "chunk", "data": "I could not find any relevant information in the knowledge base to answer your question."}
            return
            
        yield {"type": "sources", "data": context_chunks}

        # Step 2: Augment
        context_text = "\n\n---\n\n".join(
            f"[Source: {chunk['source']}, Chunk #{chunk['chunk_index']}]\n{chunk['text']}"
            for chunk in context_chunks
        )
        system_message = SYSTEM_PROMPT.format(context=context_text)

        messages: list[dict[str, str]] = [{"role": "system", "content": system_message}]
        if chat_history:
            messages.extend(chat_history)
        messages.append({"role": "user", "content": query})

        # Step 3: Stream generation
        async with await self._openai.chat.completions.create(
            model=settings.LLM_MODEL,
            messages=messages,
            temperature=0.2,
            stream=True,
        ) as stream:
            async for chunk in stream:
                token = chunk.choices[0].delta.content
                if token:
                    yield {"type": "chunk", "data": token}

from backend.services.vector_service import vector_service
rag_service = RAGService(vector_service)
